#!/usr/bin/env python

import os
import shutil
import sys

from diffusers import ControlNetModel

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import CONTROLNET_CACHE, AUX_IDS

if os.path.exists(CONTROLNET_CACHE):
    shutil.rmtree(CONTROLNET_CACHE)
os.makedirs(CONTROLNET_CACHE)

TMP_CACHE = "tmp_cache"

if os.path.exists(TMP_CACHE):
    shutil.rmtree(TMP_CACHE)
os.makedirs(TMP_CACHE)

for model in AUX_IDS:
    aux = ControlNetModel.from_pretrained(
        model,
        cache_dir=TMP_CACHE,
    )
    aux = aux.half()
    aux.save_pretrained(os.path.join(CONTROLNET_CACHE, model))

shutil.rmtree(TMP_CACHE)